# Generated by Django 6.1 on 2026-08-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'HOSPITAL',
            },
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Expired', 'Expired'), ('Used', 'Used')], default='Available', max_length=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_units', to='bloodbank.bloodbank')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_units', to='bloodbank.donor')),
            ],
            options={
                'db_table': 'BLOOD_UNIT',
            },
        ),
    ]
