# Generated by Django 6.1 on 2026-08-22 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_hospital_bloodunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_requested', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=10)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='bloodbank.hospital')),
            ],
            options={
                'db_table': 'BLOOD_REQUEST',
            },
        ),
        migrations.CreateModel(
            name='RequestFulfillment',
            fields=[
                ('fulfillment_id', models.AutoField(primary_key=True, serialize=False)),
                ('fulfilled_date', models.DateField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='bloodbank.bloodrequest')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='bloodbank.bloodunit')),
            ],
            options={
                'db_table': 'REQUEST_FULFILLMENT',
            },
        ),
    ]
